### ISSUE TITLE
Interceptor 

### ISSUE THREAD

**Issue by ZhuliyanRusev** [luchob/security27#1]
Здравейте, господин Балев, не мога да имплементирам Интерсептора в проекта си и няма кой да ми помогне, затова се обръщам към Вас оттук, понеже не намерих никакви Ваши контакти. Бих искал подкрепата Ви!

**Comment by luchob** [comment]
Здравей!

Може ли да пуснеш въпроса при останалите 100-на затворени и отворени ето тук - https://github.com/luchob/softuni-feb2023/issues

Предпочитам да са на едно място. Когато имам време и възможност ще се опитам да помогна.

Поздрави и може би до довечера :-)
Л.

**Comment by luchob** [comment]
Да добавя - с линк, където може да погледна проекта.

Поздрави,
Л.
